### ISSUE TITLE
Generated Two Class 

### ISSUE THREAD

**Issue by han361769045** [AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin#10]
Generated Two Class 
XXXXPermissionsDispatcher
XXX_PermissionsDispatcher
![image](https://user-images.githubusercontent.com/8857329/29022145-b646d056-7b9a-11e7-929a-730a1ef0ff3a.png)

**Comment by AleksanderMielczarek** [comment]
Hi, 

it is side effect of #8. For now there is nothing we can do with it.

Best regards
Aleksander Mielczarek

**Comment by AleksanderMielczarek** [comment]
@han361769045 @WonderCsabo it is fixed in 2.0.3.
