### ISSUE TITLE
Using with Java 1.6

### ISSUE THREAD

**Issue by ZacWolf** [AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin#2]
Hello, I'm trying to use your PermissionsDispatcherPlugin on an app that I'm creating to be backwards compatible to Java 1.6

It looks like when the annotations create the matching generated source it is using the <> typing. Is there something I can do so that it uses the full "type name", vs just using the <> supported in java 1.7+

Example:
```java
private static final class PickImagePermissionRequest implements PermissionRequest {
    private final WeakReference<CropFragment> weakTarget;

    private PickImagePermissionRequest(CropFragment target) {
      this.weakTarget = new WeakReference<>(target);
    }
```

**Comment by AleksanderMielczarek** [comment]
Hi,

what of version of Java is used to build project? Have you tried to add:

```groovy
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }
}
```

**Comment by ZacWolf** [comment]
The actual issue was in the hotchemi/PermissionsDispatcher project. It wasn't properly handling Java 1.6 Type requirements in "new". It has been resolved. THANKS!
